In [1]:
import torch

In [2]:
'''
当y是标量时,y关于向量x的导数 是一个向量 大小和x相同
'''

#创建向量变量x并初始化
x = torch.arange(4.0)
print(x)

x.requires_grad_(True)  # 等价于 `x = torch.arange(4.0, requires_grad=True)`
print(x.grad)   # 默认值是None

#2 * x.T * x
#此时y是标量
y = 2 * torch.dot(x, x)
print(y)

y.backward()
print(x.grad)

print(x.grad == 4*x)

#在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
print(y)
y.backward()
print(x.grad)

tensor([0., 1., 2., 3.])
None
tensor(28., grad_fn=<MulBackward0>)
tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])
tensor(6., grad_fn=<SumBackward0>)
tensor([1., 1., 1., 1.])


In [7]:
'''
当y是向量时,y关于向量x的导数是一个矩阵
高阶的y和高阶的x 求导的结果是一个高阶的张量
'''
x.grad.zero_()
print(x)
y = x * x
print(y)
print(y.sum())
y.backward(gradient=torch.ones(len(x)))
x.grad


tensor([0., 1., 2., 3.], requires_grad=True)
tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


tensor([0., 2., 4., 6.])

In [13]:
'''分离计算'''

x.grad.zero_()
print(x)
y =  x * x
print(y)
u = y.detach()
print(u)

z = u * x
print(z)
z.sum().backward()
print(x.grad)
print(x.grad==u)

x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([0., 1., 2., 3.], requires_grad=True)
tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)
tensor([0., 1., 4., 9.])
tensor([ 0.,  1.,  8., 27.], grad_fn=<MulBackward0>)
tensor([0., 1., 4., 9.])
tensor([True, True, True, True])


tensor([True, True, True, True])

In [18]:
'''基于python控制流的梯度计算'''

def f(a):
    b = a * 2
    t = b.norm()
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
print(a)
d = f(a)
d.backward()
print(a.grad)
print(a.grad == d / a)

tensor(-0.0662, requires_grad=True)
tensor(1638400.)
tensor(True)
