In [67]:
import torch

In [68]:
'''
标量
'''

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [69]:
'''
向量
(粗体小写)
'''
x = torch.arange(4)
print(x)

print(x[3])

'长度'
print(len(x))
'形状'
print(x.shape)

tensor([0, 1, 2, 3])
tensor(3)
4
torch.Size([4])


In [70]:
'''
矩阵
(粗体大写)
'''
A = torch.arange(20).reshape(5,-1)
print(A)

'矩阵的转置'
B = A.T
print(B)


C = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(C)
print(C == C.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [71]:
'''
张量
'''

X = torch.arange(24).reshape((2,3,4))
print(X)

A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()   # 通过分配新内存，将A的⼀个副本分配给B

print(A)
print(A + B)

print(A * B) #哈达玛积（２个形状相同的矩阵相乘）

#张量和标量的相加和相乘
a = 2
X = torch.arange(24).reshape(2,3,4)
print(a + X)
print(a * X)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])


In [72]:
'''降维'''

#向量的求和函数
x = torch.arange(4,dtype=torch.float32)
print(x)
print(x.sum())

#矩阵的求和
print(A.shape)
print(A.sum())

#输⼊的轴0的维数在输出形状中丢失
A_sum_axis0 = A.sum(axis=0)
print(A)
print(A_sum_axis0)
print(A_sum_axis0.shape)
#输⼊的轴1的维数在输出形状中消失
A_sum_axis1 = A.sum(axis=1)
print(A)
print(A_sum_axis1)
print(A_sum_axis1.shape)

#对张量所有轴求和,相当与对所有元素求和
print(A.sum(axis = [0,1]))

#与求和相关的求均值
print(A.mean())
print(A.sum() / A.numel())
#沿轴计算均值
print(A.mean(axis=0))
print(A.sum(axis=0) / A.shape[0])

tensor([0., 1., 2., 3.])
tensor(6.)
torch.Size([5, 4])
tensor(190.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([40., 45., 50., 55.])
torch.Size([4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([ 6., 22., 38., 54., 70.])
torch.Size([5])
tensor(190.)
tensor(9.5000)
tensor(9.5000)
tensor([ 8.,  9., 10., 11.])
tensor([ 8.,  9., 10., 11.])


In [73]:
'''非降维求和'''
sum_A = A.sum(axis=1,keepdim=True)
print(A)
print(sum_A)

#于sum_A在对每⾏进⾏求和后仍保持两个轴，我们可以通过⼴播将A除以sum_A。
print(A / sum_A)
#计算累积和　不改变张量的维度
print(A.cumsum(axis=0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [80]:
'''点积'''

#向量的点积
y = torch.ones(4,dtype=torch.float32)
print(x)
print(y)
print(torch.dot(x,y))
print((x.T * y).sum())
print(torch.sum(x * y))

#向量与矩阵的点积
print(A)
print(x)
print(x.shape)
print(torch.mv(A,x))

#矩阵乘积
B = torch.ones(4,3)
print(B)
print(A)
print(torch.mm(A,B))


tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)
tensor(6.)
tensor(6.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([0., 1., 2., 3.])
torch.Size([4])
tensor([ 14.,  38.,  62.,  86., 110.])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [84]:
'''
范数
向量表⽰物品(如单词、产
品或新闻⽂章)，以便最小化相似项⽬之间的距离，最⼤化不同项⽬之间的距离。通常，⽬标，或许是深度学
习算法最重要的组成部分(除了数据)，被表达为范数
'''

'''
向量范数是将向量映射到标量的函数f 范数
范数的性质
１．f(αx) = |α|f(x)
２．f(x + y) ≤ f(x) + f(y)
３．f(x) ≥ 0
L2范数：元素平方和开根号(欧基里德距离)
L1范数：元素绝对值之和
与L2范数相⽐，L1范数受异常值的影响较小


弗罗⻉尼乌斯范数(矩阵范数)：矩阵所有元素平方和的开方
'''
u = torch.tensor([3.0, -4.0])

L1 = torch.norm(u)
print(L1)
L2 = torch.abs(u).sum()
print(L2)

Lf = torch.norm(torch.ones((4,9)))
print(Lf)


tensor(5.)
tensor(7.)
tensor(6.)
