In [162]:
import torch


In [163]:
'''
1维：向量(Vector)
2维：矩阵(Matrix)
3+维：张量
'''
x = torch.arange(12)
print(x)
'形状'
print(x.shape)
'元素个数'
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [164]:
'''
reshape改变张量的形状,而不改变元素的个数和值
'''
X = x.reshape(3,4)
print(X)
print(X.shape)
print(X.numel())

X = x.reshape(-1,4)
print(X)
print(X.shape)
print(X.numel())

X = x.reshape(3,-1)
print(X)
print(X.shape)
print(X.numel())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12


In [165]:
tensor_zeros = torch.zeros((2,3,4))
tensor_ones = torch.ones((2,3,4))
'符合均值为０,标准差为１的高斯分布随机采样'
tensor_randn = torch.randn(3,4)
print(tensor_zeros)
print(tensor_ones)
print(tensor_randn)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[ 2.9281e-01, -1.0543e+00, -1.0282e+00,  1.0927e+00],
        [-2.5435e-01, -1.9436e-01, -1.0356e+00, -1.0798e+00],
        [ 5.3275e-02, -9.8743e-04, -1.2364e+00,  9.9904e-01]])


In [166]:
'最外层的列表对应于轴 0，内层的列表对应于轴 1'
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [167]:
'''
运算：
对于任意具有相同形状的张量，常⻅的标准算术运算符（+、-、*、/ 和 **(求幂)）都可以被升级为按元素运算
'''
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)
print(torch.exp(x))

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [168]:
'''
张量合并
'''
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
print(x)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(y)

print(torch.cat((X,Y),dim=0))
print(torch.cat((X,Y),dim=1))

tensor([1., 2., 4., 8.])
tensor([2, 2, 2, 2])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [169]:
'逐元素比较'
print(X == Y)
'元素个数'
print(X.sum())

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
tensor(66.)


In [170]:
'''
广播机制：
形状不同的张量间进行计算
'''

a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(2)

print(a)
print(b)
'矩阵 a将复制列，矩阵 b将复制⾏，然后再按元素相加'
print(a + b)

tensor([[0],
        [1],
        [2]])
tensor([0, 1])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [171]:
'''
索引和切片：
'''
print(X)
'最后一个元素'
print(X[-1])
print(X[1:3])

X[1,2] = 9
print(X)
'多元素操作'
X[0:2,:] = 12
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [172]:
'''
节省内存
'''
before = id(Y)
'Python 首先计算 Y + X，为结果分配新的内存，然后使 Y 指向内存中的这个新位置'
#Y = X + Y
'使用切片法 结果内存地址没有改变'
Y[:] = X + Y
after = id(Y)

print(before)
print(after)
print(before==after)

'''

1.机器学习中可能有数百兆的参数 我们需要在１秒内原地更新所有参数
2.很多其他引用指向旧的内存地址,如果不原地更新,某些代码可能会引用旧的参数
'''

Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
'可以使用切片法将操作的结果分配给先前分配的数组 Y[:] = <expression>'
Z[:] = X + a
print('id(Z):', id(Z))


'如果后面Ｘ不会复用 也可以使用X[:] = X + Y 或 X += Y 来减少操作的内存开销'
before = id(X)
#X[:] = X + Y
X += Y
id(X) == before

139982686273088
139982686273088
True
id(Z): 139982660088128
id(Z): 139982660088128


True

In [173]:
'''
转换为其他python对象
内存不共享
'''

A = X.numpy()
print(id(A) == id(X))
B = torch.tensor(A)
print(type(A))
print(type(B))
print(id(A) == id(B))

'将大小为１的张量转化为python标量 可以使用item函数'
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)


False
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
False


(tensor([3.5000]), 3.5, 3.5, 3)