In [19]:
import torch
from torch import nn
import torch.nn.functional as F

In [20]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))


net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
print(net)

Y = net(torch.rand(4, 8))
print(Y.mean())

Sequential(
  (0): Linear(in_features=8, out_features=128, bias=True)
  (1): CenteredLayer()
)
tensor(1.8626e-09, grad_fn=<MeanBackward0>)


In [21]:
class MyLinear(nn.Module):

    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
print(linear)
print(linear.weight)
linear(torch.rand(2, 5))


MyLinear()
Parameter containing:
tensor([[-0.4172,  0.1072,  0.5231],
        [ 1.4055, -0.9415,  0.4815],
        [ 0.1023, -0.7033,  0.0277],
        [ 0.0402,  0.0726,  1.3421],
        [-0.0565, -3.0027,  2.1857]], requires_grad=True)


tensor([[1.5207, 0.0000, 1.3021],
        [1.6539, 0.0000, 2.0151]])

In [22]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
print(net)
net(torch.rand(2, 64))

Sequential(
  (0): MyLinear()
  (1): MyLinear()
)


tensor([[0.],
        [0.]])