In [1]:
import torch
from torch import nn
import  torch.nn.functional as F

In [2]:
x = torch.randn(4)
print(x)
torch.save(x,'x-file')


x2 = torch.load('x-file')
print(x2)

tensor([ 0.8759,  0.4048, -1.5548, -0.1276])
tensor([ 0.8759,  0.4048, -1.5548, -0.1276])


In [3]:
y = torch.zeros(4)
torch.save([x,y],'x-files')
x2, y2 = torch.load('x-files')
print(x2, y2)

tensor([ 0.8759,  0.4048, -1.5548, -0.1276]) tensor([0., 0., 0., 0.])


In [4]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
print(mydict2)

{'x': tensor([ 0.8759,  0.4048, -1.5548, -0.1276]), 'y': tensor([0., 0., 0., 0.])}


In [5]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

torch.save(net.state_dict(), 'mlp.params')

clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
print(clone)

Y_clone = clone(X)
Y_clone == Y

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)


tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])