In [63]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [64]:
'''生成数据集'''

true_w = torch.tensor([2, -3.4])
true_b = 4.2

features, lables = d2l.synthetic_data(true_w, true_b, 1000)

print(features)
print(lables)

tensor([[ 1.2260,  0.2296],
        [ 0.4674,  0.2674],
        [-0.2173,  1.3189],
        ...,
        [-1.6432, -1.5170],
        [-0.5217, -3.3062],
        [-1.2720,  0.0461]])
tensor([[ 5.8728e+00],
        [ 4.2257e+00],
        [-7.0377e-01],
        [ 2.4779e+00],
        [-2.5598e+00],
        [ 4.9286e+00],
        [ 4.0302e+00],
        [ 6.3712e+00],
        [ 2.3482e+00],
        [ 1.1595e+01],
        [ 1.8935e-01],
        [ 8.2926e+00],
        [ 4.2547e+00],
        [ 1.0779e-01],
        [ 6.7068e+00],
        [ 3.5803e+00],
        [ 2.4566e+00],
        [ 3.0046e+00],
        [ 2.9627e-02],
        [ 1.9626e+00],
        [-3.1966e-01],
        [-1.5917e+00],
        [-3.9753e+00],
        [-1.3564e+00],
        [ 3.4867e+00],
        [ 9.1988e+00],
        [ 4.3536e+00],
        [ 3.7836e+00],
        [-9.0209e-01],
        [ 5.6597e+00],
        [ 5.7126e+00],
        [ 6.4311e+00],
        [ 1.7257e+00],
        [ 9.6279e+00],
        [ 9.6555e+00],
        [-1.6

In [65]:
'''读取数据'''

def load_array(data_arrays, batch_size, is_train=True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 10

data_iter = load_array((features,lables), batch_size)

next(iter(data_iter))

[tensor([[ 1.2549, -0.3753],
         [-0.1091,  1.6522],
         [-1.3641, -0.5075],
         [-0.5992, -2.1971],
         [-0.6113,  1.5405],
         [-0.8206, -0.3595],
         [-0.6761, -0.0195],
         [ 1.5009, -1.4659],
         [ 1.6038,  0.4928],
         [-1.1668, -1.6603]]),
 tensor([[ 7.9926],
         [-1.6429],
         [ 3.2070],
         [10.4695],
         [-2.2535],
         [ 3.7724],
         [ 2.9288],
         [12.1857],
         [ 5.7295],
         [ 7.5065]])]

In [66]:
'''定义模型'''

from torch import nn

net = nn.Sequential(nn.Linear(2,1))

In [67]:
'''初始化模型参数'''
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)


tensor([0.])

In [68]:
'''定义损失函数'''
loss = nn.MSELoss()


In [69]:
'''定义优化算法'''
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [70]:
'''训练'''
num_epochs = 3

for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), lables)
    print(f'epoch {epoch + 1}, loss {l:f}')

w = net[0].weight.data
print('w的估计误差：', true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差：', true_b - b)

epoch 1, loss 0.000210
epoch 2, loss 0.000099
epoch 3, loss 0.000099
w的估计误差： tensor([-0.0002, -0.0012])
b的估计误差： tensor([0.0002])
